### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#210]
An umbrella issue copied from from #205:

- [x] Install and import caproto, following a template provided by trio. [So far, so good.](https://ci.appveyor.com/project/DanielAllan/caproto)
- [ ] Switch all ioc_examples to use trio instead of curio. (#208)
- [ ] Figure out how to put the `scripts/` on the Windows PATH. Seems like the current `setup.py` configuration doesn't do the trick, unclear if we should be using `entry_points` or what. (#215)
- [x] ~Skip (on Windows only) all tests involving curio, which seems to not support Windows at all.~
- [ ] Get some epics-base stuff running to test against (???) -- or simply skip anything that doesn't test against caproto IOCs. (#215)
- [ ] Write a variant of `caproto.threading.client.SelectorThread` for Windows. (The current implementation uses a built-in Python module only available on UNIX.) (#215)
- [ ] ~Get appveyor to run on PR branches (notice this branch is on upstream).~ Maybe this works now? Not 100% sure yet.
- [x] Integrate with GitHub to get the box by the merge button.

Possibly of interest to @johnsinsheimer.
